fix: Adjusted typescript implementation for sdk
serverless/dashboard pull request #360
Opened 2023-01-09 17:31 UTC by Danwakeem

## Description
Changed the `index.d.ts` file to import the main implementation file via the `index.ts` file as well as export the `Sdk` type. This should give typescript projects typical intellisense and the ability to import the sdk like typical typescript packages.

2023-01-09 17:39 UTC, Mmarzex requested changes

2023-01-09 17:39 UTC, Mmarzex commented on node/packages/sdk/.ts-types/index.d.ts
> +      tags?: Record<string, boolean | number | string | Date | Array<any> | null>;
Probably would be better to use `Array<unknown>` here so it doesn't get caught by `tsc` that is configed for no any's.

2023-01-09 17:45 UTC, Danwakeem commented on node/packages/sdk/.ts-types/index.d.ts
> +      tags?: Record<string, boolean | number | string | Date | Array<any> | null>;
Yeah that is a good call, made this change 😎

2023-01-09 17:52 UTC, Mmarzex approved these changes

2023-01-09 18:03 UTC, merged

2023-01-11 17:13 UTC, medikoo commented
@Danwakeem this PR broke our extension builds.. all integration tests now fail. Do you know what could be the cause?

2023-01-11 17:43 UTC, Danwakeem commented
@medikoo I pulled down the `main` branch, reinstalled dependencies, ran the build in the `aws-lambda-sdk` directory, and I am seeing the failed integration tests but I am not sure what exactly the error is? 🤔 

When I look a the content of the zip file that was created and look at the content of the `extension.internal/nodejs/node_modules/@serverless/sdk/index.js` I see some references to a seemingly local path and I am wondering if that may have something to do with it? 👇 

<img width="1651" alt="Screenshot 2023-01-11 at 11 40 03 AM" src="https://user-images.githubusercontent.com/1753824/211878663-11113ece-25f3-4a6c-9485-56807e3bb8dc.png">

Does that look unusual to you? I am not sure what this looked like before but seems strange I guess. I also don't how or why this PR would have effected the builds. The build file seems to only reference the `index.js` file which is was unchanged here 🤔

2023-01-11 17:45 UTC, Danwakeem commented
Yeah when I revert this PR those local paths seem to go back to normal 🤔 Weird. I am still playing around with this a bit.

2023-01-11 17:45 UTC, medikoo commented
@Danwakeem I'm not sure as well what's going on. It appears ESbuild is trying to be smart with TS and something breaks.

Can we revert this PR, until this is figured out? I wanted to push new SDK release now, so we have it ready for tomorrow with recent changes

2023-01-11 17:46 UTC, Danwakeem commented
@medikoo Yeah that is alright with me 👍 I can work on this in the background while you get the release out.