Python sdk dev mode (RequestResponse)
serverless/dashboard pull request #556
Opened 2023-03-21 16:23 UTC by selcukcihan

Related issue https://linear.app/serverless/issue/SC-563/python-sdk-support-dev-mode

### Description
* Report request and response payloads in dev mode
* use asyncio to handle network requests asynchronously
* Rearrange unit tests to follow similar structure as in the package

### Out of scope
I've left out realtime trace reporting, which will be addressed in another PR along with eventual scheduling.

### Testing done
Unit tested

@medikoo I've tried to run the integration tests, but they are failing at the moment:
```
2023-03-21T15:43:10.118Z ℹ test Cleanup test-python-sdk-cihan
2023-03-21T15:43:10.450Z ℹ test Detached IAM policy arn:aws:iam::692593327170:policy/test-python-sdk-cihan from test-python-sdk-cihan
2023-03-21T15:43:10.470Z ℹ test Deleted 18 version of the layer test-python-sdk-cihan-internal
2023-03-21T15:43:10.642Z ℹ test Deleted IAM role test-python-sdk-cihan
2023-03-21T15:43:10.674Z ℹ test Deleted IAM policy arn:aws:iam::692593327170:policy/test-python-sdk-cihan

  9 passing (46s)
  1 failing

  1) Python: integration
       sdk-dev-mode:

      AssertionError: expected [ { …(2) }, { …(2) }, { …(2) }, …(3) ] to deeply equal [ { …(2) }, { …(2) }, { …(2) }, …(1) ]
      + expected - actual

       [
         {
      -    "name": "telemetry.warning.generated.v1"
      -    "type": "WARNING_TYPE_SDK_INTERNAL"
      -  }
      -  {
      -    "name": "telemetry.warning.generated.v1"
      -    "type": "WARNING_TYPE_SDK_INTERNAL"
      -  }
      -  {
           "name": "telemetry.error.generated.v1"
           "type": "ERROR_TYPE_CAUGHT_USER"
         }
         {
      
      at Context.<anonymous> (test/python/aws-lambda-sdk/integration.test.js:372:61)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

When I check the Cloudwatch logs, I can see that the telemetry requests failed with "Connection refused":

```
[WARNING]	2023-03-21T15:42:50.854Z	840f1842-b38f-4b9c-8308-349e3c95a34d	{'source': 'serverlessSdk', 'type': 'WARNING_TYPE_SDK_INTERNAL', 'message': "Cannot propagate telemetry: HTTPConnectionPool(host='localhost', port=2773): Max retries exceeded with url: /request-response (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd67e11e9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))", 'code': 'DEV_MODE_SERVER_ERROR'}
```

But when I publish the same layer in my account and try to use it, it actually works fine:
```
Test Event Name
test

Response
{
  "statusCode": 200,
  "body": "\"Hello from Lambda!\""
}

Function Logs
head duration: Internal initialization: 168ms
EXTENSION	Name: dev-mode-extension	State: Ready	Events: [INVOKE, SHUTDOWN]
START RequestId: 62ee7347-f020-4144-b86b-574fd70d429d Version: 18
⚡ SDK: Invocation: start
⚡ SDK: Overhead duration: Internal request:0ms
[WARNING]	2023-03-21T15:40:38.759Z	62ee7347-f020-4144-b86b-574fd70d429d	Hello world!
SERVERLESS_TELEMETRY.T.CksKEkJCNzE2enN0WlRkTTc5bXBqZhoRb3RoZXItcHl0aG9uLXRlc3QqIgoZc2VydmVybGVzcy1hd3MtbGFtYmRhLXNkaxIFMC4xLjkatwEKIDk5YTgyYjVkZGY1NGFkYzYxYmE3NzhhZGRjZmExZDI5EiA4MDM0ZDcxZWY4N2NmMGJiYTFiN2I2MzZhMDJjYmY2YiIKYXdzLmxhbWJkYSl7nb8ncXlOFzEolcxucXlOFzpPogZMogZJCgZ4ODZfNjQQAUIRb3RoZXItcHl0aG9uLXRlc3RKJDYyZWU3MzQ3LWYwMjAtNDE0NC1iODZiLTU3NGZkNzBkNDI5ZFoCMThwAWoCe30amQEKIDk4ZjJkY2E1ODFlN2Y5NWYwNDgwZjUyYWMwOTZmOTA5EiA4MDM0ZDcxZWY4N2NmMGJiYTFiN2I2MzZhMDJjYmY2YhogOTlhODJiNWRkZjU0YWRjNjFiYTc3OGFkZGNmYTFkMjkiGWF3cy5sYW1iZGEuaW5pdGlhbGl6YXRpb24pe52/J3F5Thcx4e4oV3F5Thc6AGoCe30alQEKIDhkMzIzOTk0M2NjYjZmOWY2MzM1ZjgxZmM0ODI2OTY5EiA4MDM0ZDcxZWY4N2NmMGJiYTFiN2I2MzZhMDJjYmY2YhogOTlhODJiNWRkZjU0YWRjNjFiYTc3OGFkZGNmYTFkMjkiFWF3cy5sYW1iZGEuaW52b2NhdGlvbik1c1BXcXlOFzEolcxucXlOFzoAagJ7fSLtDgogZjM0MTljNDY3YTVlZjAyNzE2YTE0OGFlODYwYTgwZGQSIDgwMzRkNzFlZjg3Y2YwYmJhMWI3YjYzNmEwMmNiZjZiGiA4ZDMyMzk5NDNjY2I2ZjlmNjMzNWY4MWZjNDgyNjk2OSHdIVhXcXlOFyoedGVsZW1ldHJ5Lndhcm5pbmcuZ2VuZXJhdGVkLnYxMgJ7fXrXDZIH0w0KDEhlbGxvIHdvcmxkIRrADSAgRmlsZSAiL29wdC9zbHMtc2RrLXB5dGhvbi9leGVjX3dyYXBwZXIucHkiLCBsaW5lIDI1LCBpbiA8bW9kdWxlPgogICAgbWFpbigpCiAgRmlsZSAiL29wdC9zbHMtc2RrLXB5dGhvbi9leGVjX3dyYXBwZXIucHkiLCBsaW5lIDIxLCBpbiBtYWluCiAgICBib290c3RyYXAubWFpbigpCiAgRmlsZSAiL3Zhci9ydW50aW1lL2Jvb3RzdHJhcC5weSIsIGxpbmUgNTcsIGluIG1haW4KICAgIGF3c2xhbWJkYXJpY21haW4ubWFpbihbb3MuZW52aXJvblsiTEFNQkRBX1RBU0tfUk9PVCJdLCBvcy5lbnZpcm9uWyJfSEFORExFUiJdXSkKICBGaWxlICIvdmFyL3J1bnRpbWUvYXdzbGFtYmRhcmljL19fbWFpbl9fLnB5IiwgbGluZSAyMSwgaW4gbWFpbgogICAgYm9vdHN0cmFwLnJ1bihhcHBfcm9vdCwgaGFuZGxlciwgbGFtYmRhX3J1bnRpbWVfYXBpX2FkZHIpCiAgRmlsZSAiL3Zhci9ydW50aW1lL2F3c2xhbWJkYXJpYy9ib290c3RyYXAucHkiLCBsaW5lIDQwNSwgaW4gcnVuCiAgICBoYW5kbGVfZXZlbnRfcmVxdWVzdCgKICBGaWxlICIvdmFyL3J1bnRpbWUvYXdzbGFtYmRhcmljL2Jvb3RzdHJhcC5weSIsIGxpbmUgMTQ5LCBpbiBoYW5kbGVfZXZlbnRfcmVxdWVzdAogICAgcmVzcG9uc2UgPSByZXF1ZXN0X2hhbmRsZXIoZXZlbnQsIGxhbWJkYV9jb250ZXh0KQogIEZpbGUgIi9vcHQvcHl0aG9uL3NlcnZlcmxlc3NfYXdzX2xhbWJkYV9zZGsvaW5zdHJ1bWVudC9fX2luaXRfXy5weSIsIGxpbmUgMzMzLCBpbiBzdHViCiAgICByZXR1cm4gYXN5bmNpby5ydW4oc2VsZi5fYXN5bmNfaGFuZGxlcih1c2VyX2hhbmRsZXIsIGV2ZW50LCBjb250ZXh0KSkKICBGaWxlICIvdmFyL2xhbmcvbGliL3B5dGhvbjMuOS9hc3luY2lvL3J1bm5lcnMucHkiLCBsaW5lIDQ0LCBpbiBydW4KICAgIHJldHVybiBsb29wLnJ1bl91bnRpbF9jb21wbGV0ZShtYWluKQogIEZpbGUgIi92YXIvbGFuZy9saWIvcHl0aG9uMy45L2FzeW5jaW8vYmFzZV9ldmVudHMucHkiLCBsaW5lIDYzNCwgaW4gcnVuX3VudGlsX2NvbXBsZXRlCiAgICBzZWxmLnJ1bl9mb3JldmVyKCkKICBGaWxlICIvdmFyL2xhbmcvbGliL3B5dGhvbjMuOS9hc3luY2lvL2Jhc2VfZXZlbnRzLnB5IiwgbGluZSA2MDEsIGluIHJ1bl9mb3JldmVyCiAgICBzZWxmLl9ydW5fb25jZSgpCiAgRmlsZSAiL3Zhci9sYW5nL2xpYi9weXRob24zLjkvYXN5bmNpby9iYXNlX2V2ZW50cy5weSIsIGxpbmUgMTkwNSwgaW4gX3J1bl9vbmNlCiAgICBoYW5kbGUuX3J1bigpCiAgRmlsZSAiL3Zhci9sYW5nL2xpYi9weXRob24zLjkvYXN5bmNpby9ldmVudHMucHkiLCBsaW5lIDgwLCBpbiBfcnVuCiAgICBzZWxmLl9jb250ZXh0LnJ1bihzZWxmLl9jYWxsYmFjaywgKnNlbGYuX2FyZ3MpCiAgRmlsZSAiL29wdC9weXRob24vc2VydmVybGVzc19hd3NfbGFtYmRhX3Nkay9pbnN0cnVtZW50L19faW5pdF9fLnB5IiwgbGluZSAzMjAsIGluIF9hc3luY19oYW5kbGVyCiAgICByZXN1bHQgPSB1c2VyX2hhbmRsZXIoZXZlbnQsIGNvbnRleHQpCiAgRmlsZSAiL3Zhci90YXNrL215bW9kdWxlL2xhbWJkYV9mdW5jdGlvbi5weSIsIGxpbmUgNywgaW4gbGFtYmRhX2hhbmRsZXIKICAgIGxvZ2dpbmcud2FybmluZygiSGVsbG8gd29ybGQhIikKICBGaWxlICIvdmFyL2xhbmcvbGliL3B5dGhvbjMuOS9sb2dnaW5nL19faW5pdF9fLnB5IiwgbGluZSAyMDgyLCBpbiB3YXJuaW5nCiAgICByb290Lndhcm5pbmcobXNnLCAqYXJncywgKiprd2FyZ3MpChABKgJ7fQ==
⚡ SDK: Telemetry send request-response
⚡ SDK: Telemetry sent in: 98ms
⚡ SDK: Telemetry send request-response
⚡ SDK: Telemetry sent in: 39ms
⚡ SDK: Overhead duration: Internal response:519ms
END RequestId: 62ee7347-f020-4144-b86b-574fd70d429d
REPORT RequestId: 62ee7347-f020-4144-b86b-574fd70d429d	Duration: 1001.74 ms	Billed Duration: 1002 ms	Memory Size: 128 MB	Max Memory Used: 103 MB	Init Duration: 1322.51 ms

Request ID
62ee7347-f020-4144-b86b-574fd70d429d
```

And I could actually see the request/response in dev mode on console:
<img width="1621" alt="Screenshot 2023-03-21 at 19 21 05" src="https://user-images.githubusercontent.com/7043904/226673514-ca903ef3-73f4-4921-985a-8aebd4c9a8fd.png">
<img width="1684" alt="Screenshot 2023-03-21 at 19 20 42" src="https://user-images.githubusercontent.com/7043904/226673539-c64da2f2-5181-4ca9-bbe8-0994f2875ee2.png">

Do I need to do anything else to activate dev mode in the integration test?

2023-03-21 16:25 UTC, medikoo commented
> Do I need to do anything else to activate dev mode in the integration test?

Yes, they need to be configured with extra dev mode layer. See: https://github.com/serverless/console/blob/22c30998b8bd980a93ef6d6a8399fe60dc6ec6b4/node/packages/aws-lambda-sdk/test/integration/index.test.js#L324-L337

2023-03-21 16:50 UTC, selcukcihan commented
> > Do I need to do anything else to activate dev mode in the integration test?
> 
> Yes, they need to be configured with extra dev mode layer. See:
> 
> https://github.com/serverless/console/blob/22c30998b8bd980a93ef6d6a8399fe60dc6ec6b4/node/packages/aws-lambda-sdk/test/integration/index.test.js#L324-L337

I've already added that configuration, the test run I pasted above is with that configured. I'll try to debug the test to see if it's actually attaching the external layer. Thanks 🙏

2023-03-21 16:55 UTC, medikoo commented
@selcukcihan I've just looked into that, and currently, we do not build external layer in python tests. To have that covered you need to pass `{ layerTypes: ['internal', 'externa'] }` options to `createCoreResources` here: https://github.com/serverless/console/blob/66ff5bb90657bca6959960f6d836efd5d986b14b/node/test/python/aws-lambda-sdk/integration.test.js#L211

2023-03-21 17:32 UTC, selcukcihan commented
> @selcukcihan I've just looked into that, and currently, we do not build external layer in python tests. To have that covered you need to pass `{ layerTypes: ['internal', 'externa'] }` options to `createCoreResources` here:
> 
> https://github.com/serverless/console/blob/66ff5bb90657bca6959960f6d836efd5d986b14b/node/test/python/aws-lambda-sdk/integration.test.js#L211

I'm now getting this error in the logs:
```
/usr/bin/env: node: No such file or directory
```

I think that's probably because the dummy dev mode extension is only compatible with Lambda NodeJS runtimes.

2023-03-21 17:34 UTC, medikoo commented
> I think that's probably because the dummy dev mode extension is only compatible with Lambda NodeJS runtimes.

Ah, yes. That's indeed the case. There's a way to mitigate it (by including the node binary in a layer). I can prepare a fix for that.

2023-03-21 18:17 UTC, selcukcihan commented
> > I think that's probably because the dummy dev mode extension is only compatible with Lambda NodeJS runtimes.
> 
> Ah, yes. That's indeed the case. There's a way to mitigate it (by including the node binary in a layer). I can prepare a fix for that.

That would be great, thank you. Once that fix is ready please let me know, I'll merge it and make sure these changes are integration tested and then will ping you so that you can review 👍

2023-03-22 09:44 UTC, medikoo commented
@selcukcihan I've prepared a fix at https://github.com/serverless/console/pull/560 - it also updates external layer build command for Python, so it builds a runtime agnostic version. Can you confirm it works?

2023-03-22 10:14 UTC, selcukcihan commented
> @selcukcihan I've prepared a fix at #560 - it also updates external layer build command for Python, so it builds a runtime agnostic version. Can you confirm it works?

Thanks @medikoo perfect 👍 

```
➜  node git:(python-base-sdk-settings) ✗ npx mocha test/python/aws-lambda-sdk/integration.test.js
2023-03-22T10:10:51.822Z ℹ test test uid: cihan


  Python: integration
2023-03-22T10:10:51.924Z ℹ test Creating core resources test-python-sdk-cihan
2023-03-22T10:11:37.019Z ℹ test Process function success-v3-8
2023-03-22T10:11:37.020Z ℹ test Process function success-v3-9
2023-03-22T10:11:37.020Z ℹ test Process function success-sampled
2023-03-22T10:11:37.021Z ℹ test Process function error-v3-8
2023-03-22T10:11:37.021Z ℹ test Process function error-v3-9
2023-03-22T10:11:37.021Z ℹ test Process function error_unhandled-v3-8
2023-03-22T10:11:37.021Z ℹ test Process function error_unhandled-v3-9
2023-03-22T10:11:37.022Z ℹ test Process function sdk-v3-8
2023-03-22T10:11:37.023Z ℹ test Process function sdk-v3-9
2023-03-22T10:11:37.023Z ℹ test Process function sdk-dev-mode
2023-03-22T10:11:37.736Z ℹ test Function sdk-dev-mode already exists, deleting and re-creating
    ✔ success-v3-8 (27314ms)
    ✔ success-v3-9
    ✔ success-sampled (1734ms)
    ✔ error-v3-8
    ✔ error-v3-9
    ✔ error_unhandled-v3-8
    ✔ error_unhandled-v3-9
    ✔ sdk-v3-8
    ✔ sdk-v3-9 (2923ms)
    ✔ sdk-dev-mode (3511ms)
2023-03-22T10:12:12.542Z ℹ test Cleanup test-python-sdk-cihan
2023-03-22T10:12:12.889Z ℹ test Deleted 2 version of the layer test-python-sdk-cihan-external
2023-03-22T10:12:12.891Z ℹ test Deleted 20 version of the layer test-python-sdk-cihan-internal
2023-03-22T10:12:13.892Z ℹ test Detached IAM policy arn:aws:iam::692593327170:policy/test-python-sdk-cihan from test-python-sdk-cihan
2023-03-22T10:12:14.121Z ℹ test Deleted IAM role test-python-sdk-cihan
2023-03-22T10:12:14.623Z ℹ test Deleted IAM policy arn:aws:iam::692593327170:policy/test-python-sdk-cihan


  10 passing (1m)
```

2023-03-22 10:15 UTC, selcukcihan commented
@medikoo this is now ready for review

2023-03-22 11:04 UTC, medikoo requested changes
@selcukcihan can you rebase against `main` (I've just merged #560) ?

2023-03-22 11:34 UTC, selcukcihan commented
> @selcukcihan can you rebase against `main` (I've just merged #560) ?

Done 👍

2023-03-22 11:36 UTC, medikoo requested changes
@selcukcihan it appears that CI failed

2023-03-22 11:52 UTC, medikoo requested changes
Thank you 👍

2023-03-22 11:52 UTC, medikoo commented on python/packages/aws-lambda-sdk/serverless_aws_lambda_sdk/instrument/__init__.py
> +    stringified_body = json.dumps(data)
We should strip eventual binary payload (as we do here: https://github.com/serverless/console/blob/2baa8371eb20e42f944935cd7d8eb1602f180d37/node/packages/aws-lambda-sdk/instrument/index.js#L43-L49)

2023-03-22 11:52 UTC, medikoo commented on python/packages/aws-lambda-sdk/serverless_aws_lambda_sdk/instrument/__init__.py
> +        return None
In this case we should also issue a _notice_ event as it's done here: https://github.com/serverless/console/blob/2baa8371eb20e42f944935cd7d8eb1602f180d37/node/packages/aws-lambda-sdk/instrument/index.js#L54-L56

2023-03-22 11:52 UTC, medikoo commented on python/packages/aws-lambda-sdk/serverless_aws_lambda_sdk/instrument/lib/scheduled_spans.py
> +    pass
What's the purpose of this function?

2023-03-22 12:14 UTC, selcukcihan commented on python/packages/aws-lambda-sdk/serverless_aws_lambda_sdk/instrument/lib/scheduled_spans.py
> +    pass
That's a placeholder for upcoming feature of buffering telemetry requests.

2023-03-22 12:17 UTC, medikoo commented on python/packages/aws-lambda-sdk/serverless_aws_lambda_sdk/instrument/lib/scheduled_spans.py
> +    pass
In Node.js this function is used to flush all pending requests right before closing the invocation. Shouldn't it be used same here?

2023-03-23 12:53 UTC, selcukcihan commented on python/packages/aws-lambda-sdk/serverless_aws_lambda_sdk/instrument/lib/scheduled_spans.py
> +    pass
I've now implemented flushing, it will buffer data for 50ms. The empty implementation is still there to cater for non-dev mode.

2023-03-23 12:53 UTC, selcukcihan commented on python/packages/aws-lambda-sdk/serverless_aws_lambda_sdk/instrument/__init__.py
> +        return None
Done 👍

2023-03-23 12:53 UTC, selcukcihan commented on python/packages/aws-lambda-sdk/serverless_aws_lambda_sdk/instrument/__init__.py
> +    stringified_body = json.dumps(data)
Done 👍

2023-03-23 13:00 UTC, selcukcihan commented
@medikoo This is ready for review again, integration tests are passing and I was able to test it on my account using the latest version of dev mode extension successfully:

- I could see the request and response data
- I could see the captured events as they were generated
- Subsequent warm invocations succeeded as well, sending out the data to dev-mode extension

2023-03-23 13:01 UTC, selcukcihan commented
> @medikoo This is ready for review again, integration tests are passing and I was able to test it on my account using the latest version of dev mode extension successfully:
> 
> * I could see the request and response data
> * I could see the captured events as they were generated
> * Subsequent warm invocations succeeded as well, sending out the data to dev-mode extension

I wanted to get this out as a baseline version, I'll see how we can improve using a separate thread for these requests over the network.

2023-03-23 13:20 UTC, medikoo requested changes
Thank you @selcukcihan. We're getting closer!

2023-03-23 13:20 UTC, medikoo commented on python/packages/aws-lambda-sdk/serverless_aws_lambda_sdk/instrument/__init__.py
> +    stringified_body = json.dumps(data)
I don't see a notice event created. Am I missing something?

2023-03-23 13:20 UTC, medikoo commented on python/packages/aws-lambda-sdk/serverless_aws_lambda_sdk/instrument/__init__.py
> +        return None
Hmm.. I don't see this addressed. Has it been pushed?

2023-03-23 13:20 UTC, medikoo commented on python/packages/aws-lambda-sdk/serverless_aws_lambda_sdk/instrument/__init__.py
> +            return result
It's not an issue in this PR, but Ive just noticed. I believe those two lines should be outside of `try` clause.

As e.g. if close_trace crashes we should not treat it as user handler crash.

We can prepare fix for that in other PR

2023-03-23 13:20 UTC, medikoo commented on python/packages/aws-lambda-sdk/serverless_aws_lambda_sdk/instrument/lib/scheduled_spans.py
> +        _flush(_should_force_flush())
What if in invocation we have scenario of closed span and then 10 seconds of silence. Will that closed span be reported within 50ms since it's closure, or will it be reported only after next event to reports comes in (or invocation closes)?

Ideally it should be reported latest 50ms after bein observed

2023-03-23 13:27 UTC, selcukcihan commented on python/packages/aws-lambda-sdk/serverless_aws_lambda_sdk/instrument/__init__.py
> +            return result
> Hmm.. I don't see this addressed. Has it been pushed?

It should have been pushed, I can see it now, can you check again please?

> It's not an issue in this PR, but Ive just noticed. I believe those two lines should be outside of try clause.
>
> As e.g. if close_trace crashes we should not treat it as user handler crash.
>
> We can prepare fix for that in other PR

Good catch, noted, I'll check this and prepare another PR.

2023-03-23 13:28 UTC, selcukcihan commented on python/packages/aws-lambda-sdk/serverless_aws_lambda_sdk/instrument/lib/scheduled_spans.py
> +        _flush(_should_force_flush())
Very good observation, yes in that case, it won't be reported until the next event which we don't have control over. Another reason for switching to multithreaded mode, where we'll have full control over when we can send out the request.

2023-03-27 11:05 UTC, medikoo approved these changes
Ouststanding work @selcukcihan Thank you!

2023-03-27 11:18 UTC, merged