feat: Add Structured Logging error capture integration test
serverless/dashboard pull request #643
Opened 2023-04-13 20:43 UTC by Mmarzex

2023-04-13 21:01 UTC, Danwakeem commented on .github/workflows/node-integrate.yml
Don’t forget to reset this 😎

2023-04-13 21:02 UTC, Danwakeem requested changes
Looks good just don’t forget to rest the action file 👍

2023-04-13 21:12 UTC, Mmarzex commented
hmm our integration tests seem to be running out of memory or something. Any ideas on that @Danwakeem ?

2023-04-13 21:15 UTC, Danwakeem commented
@Mmarzex unfortunately I think you just have to wait a minute or two before the memory issue fixes itself 😢

2023-04-13 21:45 UTC, Mmarzex commented
I did wait a while between trying again 😢

2023-04-14 01:00 UTC, Mmarzex commented
@Danwakeem I set the integration tests to increase the javascript heap size. I think the addition of the new dependencies for the structured log tests was too much with the default.

2023-04-14 01:02 UTC, Danwakeem approved these changes
Looking good 😎

2023-04-14 13:06 UTC, merged