Handle import errors
serverless/dashboard pull request #726
Opened 2023-05-08 10:07 UTC by selcukcihan

### Description
* Related issue https://linear.app/serverless/issue/SC-977/user-thetie-seeing-error-in-production-mode-with-python-sdk
* Handle import errors from the SDK (including 3rd party dependencies) by falling back to just executing the customer's handler function.

### Testing done
* Reproduced in a unit test
* Unit/integration tested

2023-05-08 10:09 UTC, selcukcihan commented
@medikoo ready for review 🙏

2023-05-09 08:29 UTC, medikoo requested changes
@selcukcihan There are conflicts, it looks it needs rebase with main

2023-05-09 08:30 UTC, medikoo commented
@selcukcihan still, let's postpone this work until we agree on final solution in Linear. I'll convert it to draft for a meanitime

2023-05-16 13:53 UTC, selcukcihan commented
> @selcukcihan still, let's postpone this work until we agree on final solution in Linear. I'll convert it to draft for a meanitime

Thanks @medikoo I think this is still relevant and a good practice to implement, after we solve the problem of managing conflicting versions we should bake this in as well.

2023-05-16 14:03 UTC, medikoo commented
> Thanks @medikoo I think this is still relevant and a good practice to implement, after we solve the problem of managing conflicting versions we should bake this in as well.

But if we ensure that we import the module we packaged, then there's no chance that import may crash, right?

2023-05-16 14:17 UTC, selcukcihan commented
> > Thanks @medikoo I think this is still relevant and a good practice to implement, after we solve the problem of managing conflicting versions we should bake this in as well.
> 
> But if we ensure that we import the module we packaged, then there's no chance that import may crash, right?

Yes 💯

2023-06-21 15:00 UTC, medikoo commented
Closing as I believe with taken approach is not longer needed

2023-06-21 15:00 UTC, closed without merging